run:
  tests: false
  timeout: 5m

linters-settings:
  cyclop:
    max-complexity: 12
    skip-tests: true
  funlen:
    lines: 80
  gofumpt:
    extra-rules: true
  gosec:
    excludes:
      - G103
      - G115

linters:
  enable-all: true
  disable:
    - execinquery # deprecated
    - exportloopref # deprecated
    - gomnd # deprecated
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - gochecknoglobals
    - ireturn
    - mnd
    - nlreturn
    - varnamelen
    - wrapcheck
    - wsl

issues:
  exclude-use-default: false
  exclude-rules:
    - path: internal/bytes/buffer.go
      linters:
        - govet
    - path: generate.go
      linters:
        - lll
