run:
  tests: false
  timeout: 5m
linters:
  enable-all: true
  disable:
    - exhaustive
    - exhaustivestruct
    - gochecknoglobals
    - gocognit
    - gocyclo
    - gomnd
    - interfacer
    - nestif
    - nlreturn
    - maligned
    - scopelint
    - wrapcheck
    - wsl

issues:
  exclude-rules:
    - path: internal/bytes/buffer.go
      linters:
        - forcetypeassert